services:
  nginx:
    image: nginx:1.27
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  app:
    build:
      context: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html
    ports:
      - 9000:9000

  mysql:
    image: mysql:8.0.40
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - ${DB_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel_local}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}

volumes:
  mysql_data:
